require("tests/test_helper")
local constants = require("go_task.constants")

describe("constants", function()
  describe("PLUGIN_NAME", function()
    it("should be set to 'go-task.nvim'", function()
      expect(constants.PLUGIN_NAME):toBe("go-task.nvim")
    end)
  end)

  describe("DEFAULT_TASK_BIN", function()
    it("should be set to 'task'", function()
      expect(constants.DEFAULT_TASK_BIN):toBe("task")
    end)
  end)

  describe("DEFAULT_TASKFILE", function()
    it("should be set to 'Taskfile.yml'", function()
      expect(constants.DEFAULT_TASKFILE):toBe("Taskfile.yml")
    end)
  end)

  describe("TASKFILE_NAMES", function()
    it("should contain both Taskfile.yml and Taskfile.yaml", function()
      expect(constants.TASKFILE_NAMES):toContain("Taskfile.yml")
      expect(constants.TASKFILE_NAMES):toContain("Taskfile.yaml")
      expect(#constants.TASKFILE_NAMES):toBe(2)
    end)
  end)

  describe("GO_PROJECT_INDICATORS", function()
    it("should contain go.mod and *.go", function()
      expect(constants.GO_PROJECT_INDICATORS):toContain("go.mod")
      expect(constants.GO_PROJECT_INDICATORS):toContain("*.go")
      expect(#constants.GO_PROJECT_INDICATORS):toBe(2)
    end)
  end)

  describe("TERMINAL_OPTIONS", function()
    it("should have correct terminal window configuration", function()
      expect(constants.TERMINAL_OPTIONS):toHaveProperty("relative")
      expect(constants.TERMINAL_OPTIONS):toHaveProperty("width")
      expect(constants.TERMINAL_OPTIONS):toHaveProperty("height")
      expect(constants.TERMINAL_OPTIONS):toHaveProperty("row")
      expect(constants.TERMINAL_OPTIONS):toHaveProperty("col")
      expect(constants.TERMINAL_OPTIONS):toHaveProperty("style")
      expect(constants.TERMINAL_OPTIONS):toHaveProperty("border")
      expect(constants.TERMINAL_OPTIONS):toHaveProperty("title")
      expect(constants.TERMINAL_OPTIONS):toHaveProperty("title_pos")
    end)

    it("should have correct relative positioning", function()
      expect(constants.TERMINAL_OPTIONS.relative):toBe("editor")
    end)

    it("should have reasonable dimensions", function()
      expect(constants.TERMINAL_OPTIONS.width):toBeGreaterThan(0)
      expect(constants.TERMINAL_OPTIONS.height):toBeGreaterThan(0)
    end)

    it("should have centered positioning", function()
      expect(constants.TERMINAL_OPTIONS.row):toBeGreaterThanOrEqual(0)
      expect(constants.TERMINAL_OPTIONS.col):toBeGreaterThanOrEqual(0)
    end)

    it("should have minimal style", function()
      expect(constants.TERMINAL_OPTIONS.style):toBe("minimal")
    end)

    it("should have single border", function()
      expect(constants.TERMINAL_OPTIONS.border):toBe("single")
    end)

    it("should have centered title", function()
      expect(constants.TERMINAL_OPTIONS.title):toBe("Task Runner")
      expect(constants.TERMINAL_OPTIONS.title_pos):toBe("center")
    end)
  end)

  describe("BUFFER_OPTIONS", function()
    it("should have correct buffer configuration", function()
      expect(constants.BUFFER_OPTIONS):toHaveProperty("buftype")
      expect(constants.BUFFER_OPTIONS):toHaveProperty("modifiable")
      expect(constants.BUFFER_OPTIONS):toHaveProperty("swapfile")
      expect(constants.BUFFER_OPTIONS):toHaveProperty("bufhidden")
    end)

    it("should be a terminal buffer", function()
      expect(constants.BUFFER_OPTIONS.buftype):toBe("terminal")
    end)

    it("should be modifiable", function()
      expect(constants.BUFFER_OPTIONS.modifiable):toBe(true)
    end)

    it("should not have swapfile", function()
      expect(constants.BUFFER_OPTIONS.swapfile):toBe(false)
    end)

    it("should hide when not visible", function()
      expect(constants.BUFFER_OPTIONS.bufhidden):toBe("hide")
    end)
  end)

  describe("WINDOW_OPTIONS", function()
    it("should have correct window configuration", function()
      expect(constants.WINDOW_OPTIONS):toHaveProperty("number")
      expect(constants.WINDOW_OPTIONS):toHaveProperty("relativenumber")
      expect(constants.WINDOW_OPTIONS):toHaveProperty("signcolumn")
      expect(constants.WINDOW_OPTIONS):toHaveProperty("foldcolumn")
      expect(constants.WINDOW_OPTIONS):toHaveProperty("list")
      expect(constants.WINDOW_OPTIONS):toHaveProperty("spell")
      expect(constants.WINDOW_OPTIONS):toHaveProperty("wrap")
    end)

    it("should hide line numbers", function()
      expect(constants.WINDOW_OPTIONS.number):toBe(false)
      expect(constants.WINDOW_OPTIONS.relativenumber):toBe(false)
    end)

    it("should hide sign column", function()
      expect(constants.WINDOW_OPTIONS.signcolumn):toBe("no")
    end)

    it("should hide fold column", function()
      expect(constants.WINDOW_OPTIONS.foldcolumn):toBe("0")
    end)

    it("should disable list mode", function()
      expect(constants.WINDOW_OPTIONS.list):toBe(false)
    end)

    it("should disable spell checking", function()
      expect(constants.WINDOW_OPTIONS.spell):toBe(false)
    end)

    it("should disable line wrapping", function()
      expect(constants.WINDOW_OPTIONS.wrap):toBe(false)
    end)
  end)
end) 